AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id

  Key:
    Type: AWS::EC2::KeyPair::KeyName

  AppserverAMI:
    Type: AWS::EC2::Image::Id

  HaProxyAMI:
    Type: AWS::EC2::Image::Id

  AZ1:
    Type: AWS::EC2::AvailabilityZone::Name

  AZ2:
    Type: AWS::EC2::AvailabilityZone::Name

  Accesskey:
    Type: String

  SecretKey:
    Type: String

Resources:
  
  SecurityGroups:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:  https://marfeelrafaelfranco.s3-eu-west-1.amazonaws.com/Security/SecGroups.yml
      Parameters:
        VPCId: !Ref VPCId
  
  AppserverTier:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:  https://marfeelrafaelfranco.s3-eu-west-1.amazonaws.com/APPSERVER/Appserver.yml
      Parameters:
        AppserverSG: !GetAtt SecurityGroups.Outputs.AppserverSG
        AMI: !Ref AppserverAMI
        Key: !Ref Key
        AZ1: !Ref AZ1
        AZ2: !Ref AZ2
  
  HAPROXY:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:  https://marfeelrafaelfranco.s3-eu-west-1.amazonaws.com/HAPROXY/HAproxy.yml
      Parameters:
        HAproxySG: !GetAtt SecurityGroups.Outputs.HAproxySG
        AMI: !Ref HaProxyAMI
        Key: !Ref Key
        AppserverTier: !GetAtt AppserverTier.Outputs.AppserverAutoScalingGroup
        Accesskey: !Ref Accesskey
        SecretKey: !Ref SecretKey
  
 
Outputs:

  HaProxyIP:
    Value: !GetAtt HAPROXY.Outputs.HAproxyIP