AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template deploys the haproxy instance
Parameters:
  HAproxySG:
    Type: String
  
  AMI:
    Type: AWS::EC2::Image::Id

  Key:
    Type: String

  AppserverTier:
    Type: String
  
  Accesskey:
    Type: String

  SecretKey:
    Type: String

Resources:
  
  HAProxyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.nano
      KeyName: !Ref Key
      SecurityGroupIds: 
        - !Ref HAproxySG
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install awscli haproxy python python3-boto3 -y
            aws configure set aws_access_key_id ${Accesskey}
            aws configure set aws_secret_access_key ${SecretKey}
            aws configure set default.region ${AWS::Region}
            cd /opt
            wget https://marfeelrafaelfranco.s3-eu-west-1.amazonaws.com/HAPROXY/scaleips.py
            cd /etc/haproxy
            rm haproxy.cfg
            wget https://marfeelrafaelfranco.s3-eu-west-1.amazonaws.com/HAPROXY/haproxy.cfg
            crontab -l > mycron
            echo "3 * * * * python /opt/scaleips.py &" >> mycron
            crontab mycron
            rm mycron
            



Outputs:

  HAproxyIP:
    Value: !GetAtt  HAProxyInstance.PublicIp